### ISSUE TITLE
UTF encode error while generating epub

### ISSUE THREAD

**Issue by ShashankYadav** [de3sw2aq1/wattpad-ebook-scraper#1]
Here is the python error traceback: 

command : python scrape.py http://www.wattpad.com/story/265762-invisible-a-love-story-watty-awards-2011

Traceback (most recent call last):
  File "scrape.py", line 101, in <module>
    download_story(story_url)
  File "scrape.py", line 91, in download_story
    book.make(book.title + '.epub')
  File "/home/bitraid/wattpad-ebook-scraper-master/ez_epub.py", line 57, in make
    self.impl.create_book(output)
  File "/usr/local/lib/python2.7/dist-packages/epubbuilder/epubbuilder.py", line 415, in create_book
    self.__write_items(zip_outout)
  File "/usr/local/lib/python2.7/dist-packages/epubbuilder/epubbuilder.py", line 390, in __write_items
    content = content.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 812: ordinal not in range(128)

**Comment by de3sw2aq1** [comment]
This should be fixed by #3. I successfully downloaded the story you listed.

Please reopen this issue if it still doesn't work for you.
