### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by RishabhBhatnagar** [de3sw2aq1/wattpad-ebook-scraper#17]
$  python scrape.py http://www.wattpad.com/story/9876543-example-story http://www.wattpad.com/story/9999999-example-story-2                                                                                 Story "He Doesn't Know.": 9876543                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                            File "scrape.py", line 134, in                                                                                                                                                                        main()                                                                                                                                                                                                    File "scrape.py", line 128, in main                                                                                                                                                                           download_story(story_id)                                                                                                                                                                                  File "scrape.py", line 75, in download_story                                                                                                                                                                  print('Skipping "{chapter_title}": {chapter_id}, part is deleted'.format(chapter_title=chapter_title, chapter_id=chapter_id))                                                                           UnboundLocalError: local variable 'chapter_id' referenced before assignment
--

This is the exact issue i am getting. This is a minor error.

**Comment by de3sw2aq1** [comment]
Sorry, I am no longer maintaining this project. I recommend you try https://github.com/JimmXinu/FanFicFare instead. It contains a Wattpad downloader (based off this project) among many other downloaders for stories.

**Comment by RishabhBhatnagar** [comment]
Please merge the pr and close this issue. If it is unmaintained, I would contribute to another repository thereafter.
